

buildMain:
	g++ Person.cpp ListNode.cpp LinkedList.cpp HashTable.cpp main.cpp -o main
runMain:
	./main
cleanMain:
	rm main
buildTester:
	g++ Person.cpp ListNode.cpp LinkedList.cpp HashTable.cpp HashTableTester.cpp -o tester
runTester:
	./tester
cleanTester:
	rm tester

